!ArenaConfig
arenas:
  0: !Arena
    passMark: 0
    timeLimit: 25
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 5, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 15}
      - !Vector3 {x: 18.5, y: 0, z: 10}
      - !Vector3 {x: 21.5, y: 0, z: 10}
      - !Vector3 {x: 16.5, y: 0, z: 30}
      - !Vector3 {x: 23.5, y: 0, z: 30}
      - !Vector3 {x: 18.75, y: 0, z: 35}
      - !Vector3 {x: 21.25, y: 0, z: 35}
      rotations: [0, 0, 0, 258.7, 101.3, 258.7, 101.3]
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 2, y: 1, z: 30}
      - !Vector3 {x: .5, y: 5, z: 20}
      - !Vector3 {x: .5, y: 5, z: 20}
      - !Vector3 {x: 20.3, y: 5, z: .5}
      - !Vector3 {x: 20.3, y: 5, z: .5}
      - !Vector3 {x: 10.1, y: 5, z: .5}
      - !Vector3 {x: 10.1, y: 5, z: .5}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 18, y: 0, z: 32}      
      sizes:
      - !Vector3 {x: 1.5, y: 1.5, z: 1.5}

  1: !Arena
    passMark: 0
    timeLimit: 25
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 1, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 15}
      - !Vector3 {x: 18.5, y: 0, z: 10}
      - !Vector3 {x: 21.5, y: 0, z: 10}
      - !Vector3 {x: 16.5, y: 0, z: 30}
      - !Vector3 {x: 23.5, y: 0, z: 30}
      - !Vector3 {x: 18.75, y: 0, z: 35}
      - !Vector3 {x: 21.25, y: 0, z: 35}
      rotations: [0, 0, 0, 258.7, 101.3, 258.7, 101.3]
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 2, y: 1, z: 30}
      - !Vector3 {x: .5, y: 5, z: 20}
      - !Vector3 {x: .5, y: 5, z: 20}
      - !Vector3 {x: 20.3, y: 5, z: .5}
      - !Vector3 {x: 20.3, y: 5, z: .5}
      - !Vector3 {x: 10.1, y: 5, z: .5}
      - !Vector3 {x: 10.1, y: 5, z: .5}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 22, y: 0, z: 32}      
      sizes:
      - !Vector3 {x: 1.5, y: 1.5, z: 1.5}

  2: !Arena
    passMark: 0
    timeLimit: 25
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 15, y: 5, z: 15}
      rotations: [225]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 4.5, y: 5, z: 4.5}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  
  3: !Arena
    passMark: 0
    timeLimit: 25
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 5}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 10, y: 0, z: 10.25}
      - !Vector3 {x: 30, y: 0, z: 10.25}
      - !Vector3 {x: 17.78, y: 0, z: 20}
      - !Vector3 {x: 22.22, y: 0, z: 20}
      - !Vector3 {x: 20, y: 0, z: 30.25}
      rotations: [45, 135, 258.7, 101.3, 0]
      colors: 
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 27.75, y: 5, z: .5}
      - !Vector3 {x: 27.75, y: 5, z: .5}
      - !Vector3 {x: 20, y: 5, z: .5}
      - !Vector3 {x: 20, y: 5, z: .5}
      - !Vector3 {x: 40, y: 5, z: .5}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 30, y: 0, z: 25}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 10, y: 0, z: 25}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}